export interface IImgurImageResponse {
    id: string,
    title: string,
    description: string,
    datetime: number,
    type: string,
    animated: boolean,
    width: number,
    height: number,
    size: number,
    views: number,
    bandwidth: number,
    deletehash: string,
    name: string,
    section: string,
    link: string,
    gifv: string,
    mp4: string,
    mp4_size: string,
    looping: boolean,
    favorite: boolean,
    nsfw: boolean,
    vote: string,
    in_gallery: boolean,
}
